//
//  Chart.swift
//  Lazy
//
//  Created by Kiran on 1/31/16.
//  Copyright (c) 2016 Lazy. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class Chart : NSObject {

    //// Drawing Methods

    public class func drawChart(frame frame: CGRect = CGRectMake(0, 0, 100, 100), ratio: CGFloat = 0.659) {
        //// Color Declarations
        let color = UIColor(red: 0.000, green: 0.741, blue: 0.612, alpha: 1.000)
        let color2 = UIColor(red: 1.000, green: 0.212, blue: 0.420, alpha: 1.000)
        let color3 = UIColor(red: 0.200, green: 0.286, blue: 0.365, alpha: 1.000)
        let fillColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)

        //// Variable Declarations
        let angle: CGFloat = ratio * 360 - 90


        //// Subframes
        let group: CGRect = CGRectMake(frame.minX + floor(frame.width * 0.00000 + 0.5), frame.minY + floor(frame.height * 0.00000 + 0.5), floor(frame.width * 1.00000 + 0.5) - floor(frame.width * 0.00000 + 0.5), floor(frame.height * 1.00000 + 0.5) - floor(frame.height * 0.00000 + 0.5))


        //// Group
        //// Oval Drawing
        let ovalPath = UIBezierPath(ovalInRect: CGRectMake(group.minX + floor(group.width * 0.00000 + 0.5), group.minY + floor(group.height * 0.00000 + 0.5), floor(group.width * 1.00000 + 0.5) - floor(group.width * 0.00000 + 0.5), floor(group.height * 1.00000 + 0.5) - floor(group.height * 0.00000 + 0.5)))
        color.setFill()
        ovalPath.fill()


        //// Second Drawing
        let secondRect = CGRectMake(group.minX + floor(group.width * 0.00000 + 0.5), group.minY + floor(group.height * 0.00000 + 0.5), floor(group.width * 1.00000 + 0.5) - floor(group.width * 0.00000 + 0.5), floor(group.height * 1.00000 + 0.5) - floor(group.height * 0.00000 + 0.5))
        let secondPath = UIBezierPath()
        secondPath.addArcWithCenter(CGPointMake(secondRect.midX, secondRect.midY), radius: secondRect.width / 2, startAngle: -angle * CGFloat(M_PI)/180, endAngle: 90 * CGFloat(M_PI)/180, clockwise: true)
        secondPath.addLineToPoint(CGPointMake(secondRect.midX, secondRect.midY))
        secondPath.closePath()

        color2.setFill()
        secondPath.fill()


        //// Inside Drawing
        let insidePath = UIBezierPath(ovalInRect: CGRectMake(group.minX + floor(group.width * 0.12000 + 0.5), group.minY + floor(group.height * 0.11000 + 0.5), floor(group.width * 0.89000 + 0.5) - floor(group.width * 0.12000 + 0.5), floor(group.height * 0.88000 + 0.5) - floor(group.height * 0.11000 + 0.5)))
        color3.setFill()
        insidePath.fill()


        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(group.minX + 0.56882 * group.width, group.minY + 0.33544 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.63000 * group.width, group.minY + 0.33544 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.63000 * group.width, group.minY + 0.35058 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.37000 * group.width, group.minY + 0.35058 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.37000 * group.width, group.minY + 0.33544 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.43118 * group.width, group.minY + 0.33544 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.43118 * group.width, group.minY + 0.32029 * group.height))
        bezierPath.addCurveToPoint(CGPointMake(group.minX + 0.46172 * group.width, group.minY + 0.29000 * group.height), controlPoint1: CGPointMake(group.minX + 0.43118 * group.width, group.minY + 0.30345 * group.height), controlPoint2: CGPointMake(group.minX + 0.44485 * group.width, group.minY + 0.29000 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.53828 * group.width, group.minY + 0.29000 * group.height))
        bezierPath.addCurveToPoint(CGPointMake(group.minX + 0.56882 * group.width, group.minY + 0.32029 * group.height), controlPoint1: CGPointMake(group.minX + 0.55512 * group.width, group.minY + 0.29000 * group.height), controlPoint2: CGPointMake(group.minX + 0.56882 * group.width, group.minY + 0.30356 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.56882 * group.width, group.minY + 0.33544 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.56882 * group.width, group.minY + 0.33544 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.56882 * group.width, group.minY + 0.33544 * group.height))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(group.minX + 0.37000 * group.width, group.minY + 0.36573 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.37000 * group.width, group.minY + 0.65349 * group.height))
        bezierPath.addCurveToPoint(CGPointMake(group.minX + 0.41588 * group.width, group.minY + 0.69895 * group.height), controlPoint1: CGPointMake(group.minX + 0.37000 * group.width, group.minY + 0.67859 * group.height), controlPoint2: CGPointMake(group.minX + 0.39040 * group.width, group.minY + 0.69895 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.58412 * group.width, group.minY + 0.69895 * group.height))
        bezierPath.addCurveToPoint(CGPointMake(group.minX + 0.63000 * group.width, group.minY + 0.65349 * group.height), controlPoint1: CGPointMake(group.minX + 0.60946 * group.width, group.minY + 0.69895 * group.height), controlPoint2: CGPointMake(group.minX + 0.63000 * group.width, group.minY + 0.67860 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.63000 * group.width, group.minY + 0.36573 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.37000 * group.width, group.minY + 0.36573 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.37000 * group.width, group.minY + 0.36573 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.37000 * group.width, group.minY + 0.36573 * group.height))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(group.minX + 0.38529 * group.width, group.minY + 0.38088 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.38529 * group.width, group.minY + 0.65365 * group.height))
        bezierPath.addCurveToPoint(CGPointMake(group.minX + 0.41576 * group.width, group.minY + 0.68380 * group.height), controlPoint1: CGPointMake(group.minX + 0.38529 * group.width, group.minY + 0.67030 * group.height), controlPoint2: CGPointMake(group.minX + 0.39896 * group.width, group.minY + 0.68380 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.58424 * group.width, group.minY + 0.68380 * group.height))
        bezierPath.addCurveToPoint(CGPointMake(group.minX + 0.61471 * group.width, group.minY + 0.65365 * group.height), controlPoint1: CGPointMake(group.minX + 0.60107 * group.width, group.minY + 0.68380 * group.height), controlPoint2: CGPointMake(group.minX + 0.61471 * group.width, group.minY + 0.67020 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.61471 * group.width, group.minY + 0.38088 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.38529 * group.width, group.minY + 0.38088 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.38529 * group.width, group.minY + 0.38088 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.38529 * group.width, group.minY + 0.38088 * group.height))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(group.minX + 0.43118 * group.width, group.minY + 0.41117 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.43118 * group.width, group.minY + 0.65351 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.44647 * group.width, group.minY + 0.65351 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.44647 * group.width, group.minY + 0.41117 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.43118 * group.width, group.minY + 0.41117 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.43118 * group.width, group.minY + 0.41117 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.43118 * group.width, group.minY + 0.41117 * group.height))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(group.minX + 0.49235 * group.width, group.minY + 0.41117 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.49235 * group.width, group.minY + 0.65351 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.50765 * group.width, group.minY + 0.65351 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.50765 * group.width, group.minY + 0.41117 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.49235 * group.width, group.minY + 0.41117 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.49235 * group.width, group.minY + 0.41117 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.49235 * group.width, group.minY + 0.41117 * group.height))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(group.minX + 0.55353 * group.width, group.minY + 0.41117 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.55353 * group.width, group.minY + 0.65351 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.56882 * group.width, group.minY + 0.65351 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.56882 * group.width, group.minY + 0.41117 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.55353 * group.width, group.minY + 0.41117 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.55353 * group.width, group.minY + 0.41117 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.55353 * group.width, group.minY + 0.41117 * group.height))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(group.minX + 0.46181 * group.width, group.minY + 0.30515 * group.height))
        bezierPath.addCurveToPoint(CGPointMake(group.minX + 0.44647 * group.width, group.minY + 0.32029 * group.height), controlPoint1: CGPointMake(group.minX + 0.45334 * group.width, group.minY + 0.30515 * group.height), controlPoint2: CGPointMake(group.minX + 0.44647 * group.width, group.minY + 0.31187 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.44647 * group.width, group.minY + 0.33544 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.55353 * group.width, group.minY + 0.33544 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.55353 * group.width, group.minY + 0.32029 * group.height))
        bezierPath.addCurveToPoint(CGPointMake(group.minX + 0.53819 * group.width, group.minY + 0.30515 * group.height), controlPoint1: CGPointMake(group.minX + 0.55353 * group.width, group.minY + 0.31193 * group.height), controlPoint2: CGPointMake(group.minX + 0.54683 * group.width, group.minY + 0.30515 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.46181 * group.width, group.minY + 0.30515 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.46181 * group.width, group.minY + 0.30515 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.46181 * group.width, group.minY + 0.30515 * group.height))
        bezierPath.closePath()
        bezierPath.usesEvenOddFillRule = true;

        fillColor.setFill()
        bezierPath.fill()
    }

    public class func drawMotivate(frame frame: CGRect = CGRectMake(0, 0, 100, 100)) {
        //// Color Declarations
        let strokeColor = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)
        let fillColor2 = UIColor(red: 0.306, green: 1.000, blue: 0.733, alpha: 1.000)
        let fillColor3 = UIColor(red: 0.133, green: 0.125, blue: 0.318, alpha: 1.000)
        let fillColor4 = UIColor(red: 0.188, green: 0.173, blue: 0.345, alpha: 1.000)
        let strokeColor2 = UIColor(red: 0.133, green: 0.125, blue: 0.318, alpha: 1.000)


        //// Subframes
        let group: CGRect = CGRectMake(frame.minX + floor(frame.width * 0.28113 + 0.39) + 0.11, frame.minY + floor(frame.height * 0.15825 + 0.08) + 0.42, floor(frame.width * 0.72486 + 0.01) - floor(frame.width * 0.28113 + 0.39) + 0.37, floor(frame.height * 0.83584 + 0.33) - floor(frame.height * 0.15825 + 0.08) - 0.24)


        //// Oval Drawing
        let ovalPath = UIBezierPath(ovalInRect: CGRectMake(frame.minX + 4, frame.minY + 3, frame.width - 7, frame.height - 7))
        strokeColor.setStroke()
        ovalPath.lineWidth = 3
        ovalPath.stroke()


        //// Group
        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(group.minX + 1.00000 * group.width, group.minY + 0.59661 * group.height))
        bezierPath.addCurveToPoint(CGPointMake(group.minX + 0.67108 * group.width, group.minY + 0.37836 * group.height), controlPoint1: CGPointMake(group.minX + 1.00000 * group.width, group.minY + 0.47607 * group.height), controlPoint2: CGPointMake(group.minX + 0.85274 * group.width, group.minY + 0.37836 * group.height))
        bezierPath.addCurveToPoint(CGPointMake(group.minX + 0.34215 * group.width, group.minY + 0.59661 * group.height), controlPoint1: CGPointMake(group.minX + 0.48942 * group.width, group.minY + 0.37836 * group.height), controlPoint2: CGPointMake(group.minX + 0.34215 * group.width, group.minY + 0.47607 * group.height))
        bezierPath.addCurveToPoint(CGPointMake(group.minX + 0.53950 * group.width, group.minY + 0.83982 * group.height), controlPoint1: CGPointMake(group.minX + 0.34215 * group.width, group.minY + 0.75760 * group.height), controlPoint2: CGPointMake(group.minX + 0.53950 * group.width, group.minY + 0.75431 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.53950 * group.width, group.minY + 0.94539 * group.height))
        bezierPath.addCurveToPoint(CGPointMake(group.minX + 0.62180 * group.width, group.minY + 1.00000 * group.height), controlPoint1: CGPointMake(group.minX + 0.53950 * group.width, group.minY + 0.97555 * group.height), controlPoint2: CGPointMake(group.minX + 0.57635 * group.width, group.minY + 1.00000 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.72894 * group.width, group.minY + 1.00000 * group.height))
        bezierPath.addCurveToPoint(CGPointMake(group.minX + 0.81124 * group.width, group.minY + 0.94539 * group.height), controlPoint1: CGPointMake(group.minX + 0.77440 * group.width, group.minY + 1.00000 * group.height), controlPoint2: CGPointMake(group.minX + 0.81124 * group.width, group.minY + 0.97555 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 0.81124 * group.width, group.minY + 0.83982 * group.height))
        bezierPath.addCurveToPoint(CGPointMake(group.minX + 1.00000 * group.width, group.minY + 0.59661 * group.height), controlPoint1: CGPointMake(group.minX + 0.81124 * group.width, group.minY + 0.75101 * group.height), controlPoint2: CGPointMake(group.minX + 1.00000 * group.width, group.minY + 0.75760 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 1.00000 * group.width, group.minY + 0.59661 * group.height))
        bezierPath.addLineToPoint(CGPointMake(group.minX + 1.00000 * group.width, group.minY + 0.59661 * group.height))
        bezierPath.closePath()
        bezierPath.usesEvenOddFillRule = true;

        fillColor2.setFill()
        bezierPath.fill()


        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(group.minX + 0.55203 * group.width, group.minY + 0.92044 * group.height))
        bezier2Path.addLineToPoint(CGPointMake(group.minX + 0.44490 * group.width, group.minY + 0.92044 * group.height))
        bezier2Path.addCurveToPoint(CGPointMake(group.minX + 0.30559 * group.width, group.minY + 0.82800 * group.height), controlPoint1: CGPointMake(group.minX + 0.36807 * group.width, group.minY + 0.92044 * group.height), controlPoint2: CGPointMake(group.minX + 0.30559 * group.width, group.minY + 0.87897 * group.height))
        bezier2Path.addLineToPoint(CGPointMake(group.minX + 0.30559 * group.width, group.minY + 0.72242 * group.height))
        bezier2Path.addCurveToPoint(CGPointMake(group.minX + 0.24950 * group.width, group.minY + 0.67119 * group.height), controlPoint1: CGPointMake(group.minX + 0.30559 * group.width, group.minY + 0.70522 * group.height), controlPoint2: CGPointMake(group.minX + 0.29022 * group.width, group.minY + 0.69471 * group.height))
        bezier2Path.addCurveToPoint(CGPointMake(group.minX + 0.10825 * group.width, group.minY + 0.47922 * group.height), controlPoint1: CGPointMake(group.minX + 0.18988 * group.width, group.minY + 0.63674 * group.height), controlPoint2: CGPointMake(group.minX + 0.10825 * group.width, group.minY + 0.58956 * group.height))
        bezier2Path.addCurveToPoint(CGPointMake(group.minX + 0.49416 * group.width, group.minY + 0.22315 * group.height), controlPoint1: CGPointMake(group.minX + 0.10825 * group.width, group.minY + 0.33803 * group.height), controlPoint2: CGPointMake(group.minX + 0.28137 * group.width, group.minY + 0.22315 * group.height))
        bezier2Path.addCurveToPoint(CGPointMake(group.minX + 0.88008 * group.width, group.minY + 0.47922 * group.height), controlPoint1: CGPointMake(group.minX + 0.70695 * group.width, group.minY + 0.22315 * group.height), controlPoint2: CGPointMake(group.minX + 0.88008 * group.width, group.minY + 0.33803 * group.height))
        bezier2Path.addCurveToPoint(CGPointMake(group.minX + 0.74614 * group.width, group.minY + 0.66859 * group.height), controlPoint1: CGPointMake(group.minX + 0.88008 * group.width, group.minY + 0.58842 * group.height), controlPoint2: CGPointMake(group.minX + 0.80267 * group.width, group.minY + 0.63476 * group.height))
        bezier2Path.addCurveToPoint(CGPointMake(group.minX + 0.69134 * group.width, group.minY + 0.72242 * group.height), controlPoint1: CGPointMake(group.minX + 0.70553 * group.width, group.minY + 0.69289 * group.height), controlPoint2: CGPointMake(group.minX + 0.69134 * group.width, group.minY + 0.70312 * group.height))
        bezier2Path.addLineToPoint(CGPointMake(group.minX + 0.69134 * group.width, group.minY + 0.82800 * group.height))
        bezier2Path.addCurveToPoint(CGPointMake(group.minX + 0.55203 * group.width, group.minY + 0.92044 * group.height), controlPoint1: CGPointMake(group.minX + 0.69134 * group.width, group.minY + 0.87897 * group.height), controlPoint2: CGPointMake(group.minX + 0.62885 * group.width, group.minY + 0.92044 * group.height))
        bezier2Path.addLineToPoint(CGPointMake(group.minX + 0.55203 * group.width, group.minY + 0.92044 * group.height))
        bezier2Path.addLineToPoint(CGPointMake(group.minX + 0.55203 * group.width, group.minY + 0.92044 * group.height))
        bezier2Path.closePath()
        bezier2Path.moveToPoint(CGPointMake(group.minX + 0.49416 * group.width, group.minY + 0.29880 * group.height))
        bezier2Path.addCurveToPoint(CGPointMake(group.minX + 0.22225 * group.width, group.minY + 0.47922 * group.height), controlPoint1: CGPointMake(group.minX + 0.34422 * group.width, group.minY + 0.29880 * group.height), controlPoint2: CGPointMake(group.minX + 0.22225 * group.width, group.minY + 0.37974 * group.height))
        bezier2Path.addCurveToPoint(CGPointMake(group.minX + 0.32438 * group.width, group.minY + 0.61415 * group.height), controlPoint1: CGPointMake(group.minX + 0.22225 * group.width, group.minY + 0.55513 * group.height), controlPoint2: CGPointMake(group.minX + 0.27185 * group.width, group.minY + 0.58379 * group.height))
        bezier2Path.addCurveToPoint(CGPointMake(group.minX + 0.41959 * group.width, group.minY + 0.72242 * group.height), controlPoint1: CGPointMake(group.minX + 0.36902 * group.width, group.minY + 0.63993 * group.height), controlPoint2: CGPointMake(group.minX + 0.41959 * group.width, group.minY + 0.66916 * group.height))
        bezier2Path.addLineToPoint(CGPointMake(group.minX + 0.41959 * group.width, group.minY + 0.82800 * group.height))
        bezier2Path.addCurveToPoint(CGPointMake(group.minX + 0.44490 * group.width, group.minY + 0.84479 * group.height), controlPoint1: CGPointMake(group.minX + 0.41959 * group.width, group.minY + 0.83725 * group.height), controlPoint2: CGPointMake(group.minX + 0.43095 * group.width, group.minY + 0.84479 * group.height))
        bezier2Path.addLineToPoint(CGPointMake(group.minX + 0.55203 * group.width, group.minY + 0.84479 * group.height))
        bezier2Path.addCurveToPoint(CGPointMake(group.minX + 0.57733 * group.width, group.minY + 0.82800 * group.height), controlPoint1: CGPointMake(group.minX + 0.56597 * group.width, group.minY + 0.84479 * group.height), controlPoint2: CGPointMake(group.minX + 0.57733 * group.width, group.minY + 0.83725 * group.height))
        bezier2Path.addLineToPoint(CGPointMake(group.minX + 0.57733 * group.width, group.minY + 0.72242 * group.height))
        bezier2Path.addCurveToPoint(CGPointMake(group.minX + 0.66977 * group.width, group.minY + 0.61242 * group.height), controlPoint1: CGPointMake(group.minX + 0.57733 * group.width, group.minY + 0.66776 * group.height), controlPoint2: CGPointMake(group.minX + 0.62643 * group.width, group.minY + 0.63836 * group.height))
        bezier2Path.addCurveToPoint(CGPointMake(group.minX + 0.76607 * group.width, group.minY + 0.47922 * group.height), controlPoint1: CGPointMake(group.minX + 0.71928 * group.width, group.minY + 0.58278 * group.height), controlPoint2: CGPointMake(group.minX + 0.76607 * group.width, group.minY + 0.55478 * group.height))
        bezier2Path.addCurveToPoint(CGPointMake(group.minX + 0.49416 * group.width, group.minY + 0.29880 * group.height), controlPoint1: CGPointMake(group.minX + 0.76607 * group.width, group.minY + 0.37974 * group.height), controlPoint2: CGPointMake(group.minX + 0.64410 * group.width, group.minY + 0.29880 * group.height))
        bezier2Path.addLineToPoint(CGPointMake(group.minX + 0.49416 * group.width, group.minY + 0.29880 * group.height))
        bezier2Path.addLineToPoint(CGPointMake(group.minX + 0.49416 * group.width, group.minY + 0.29880 * group.height))
        bezier2Path.closePath()
        bezier2Path.usesEvenOddFillRule = true;

        fillColor3.setFill()
        bezier2Path.fill()


        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(roundedRect: CGRectMake(group.minX + floor(group.width * 0.29663 + 0.34) + 0.16, group.minY + floor(group.height * 0.73090 + 0.47) + 0.03, floor(group.width * 0.68313 + 0.19) - floor(group.width * 0.29663 + 0.34) + 0.15, floor(group.height * 0.80764 + 0.27) - floor(group.height * 0.73090 + 0.47) + 0.2), cornerRadius: 2)
        fillColor3.setFill()
        rectanglePath.fill()


        //// Bezier 3 Drawing
        let bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPointMake(group.minX + 0.40930 * group.width, group.minY + 0.80070 * group.height))
        bezier3Path.addCurveToPoint(CGPointMake(group.minX + 0.43919 * group.width, group.minY + 0.85531 * group.height), controlPoint1: CGPointMake(group.minX + 0.40930 * group.width, group.minY + 0.83086 * group.height), controlPoint2: CGPointMake(group.minX + 0.40937 * group.width, group.minY + 0.85531 * group.height))
        bezier3Path.addLineToPoint(CGPointMake(group.minX + 0.55772 * group.width, group.minY + 0.85531 * group.height))
        bezier3Path.addCurveToPoint(CGPointMake(group.minX + 0.58761 * group.width, group.minY + 0.80070 * group.height), controlPoint1: CGPointMake(group.minX + 0.58755 * group.width, group.minY + 0.85531 * group.height), controlPoint2: CGPointMake(group.minX + 0.58761 * group.width, group.minY + 0.83086 * group.height))
        bezier3Path.addLineToPoint(CGPointMake(group.minX + 0.40930 * group.width, group.minY + 0.80070 * group.height))
        bezier3Path.addLineToPoint(CGPointMake(group.minX + 0.40930 * group.width, group.minY + 0.80070 * group.height))
        bezier3Path.addLineToPoint(CGPointMake(group.minX + 0.40930 * group.width, group.minY + 0.80070 * group.height))
        bezier3Path.closePath()
        bezier3Path.usesEvenOddFillRule = true;

        fillColor4.setFill()
        bezier3Path.fill()


        //// Bezier 4 Drawing
        let bezier4Path = UIBezierPath()
        bezier4Path.moveToPoint(CGPointMake(group.minX + 0.40930 * group.width, group.minY + 0.80070 * group.height))
        bezier4Path.addCurveToPoint(CGPointMake(group.minX + 0.43919 * group.width, group.minY + 0.85531 * group.height), controlPoint1: CGPointMake(group.minX + 0.40930 * group.width, group.minY + 0.83086 * group.height), controlPoint2: CGPointMake(group.minX + 0.40937 * group.width, group.minY + 0.85531 * group.height))
        bezier4Path.addLineToPoint(CGPointMake(group.minX + 0.55772 * group.width, group.minY + 0.85531 * group.height))
        bezier4Path.addCurveToPoint(CGPointMake(group.minX + 0.58761 * group.width, group.minY + 0.80070 * group.height), controlPoint1: CGPointMake(group.minX + 0.58755 * group.width, group.minY + 0.85531 * group.height), controlPoint2: CGPointMake(group.minX + 0.58761 * group.width, group.minY + 0.83086 * group.height))
        bezier4Path.addLineToPoint(CGPointMake(group.minX + 0.40930 * group.width, group.minY + 0.80070 * group.height))
        bezier4Path.addLineToPoint(CGPointMake(group.minX + 0.40930 * group.width, group.minY + 0.80070 * group.height))
        bezier4Path.addLineToPoint(CGPointMake(group.minX + 0.40930 * group.width, group.minY + 0.80070 * group.height))
        bezier4Path.closePath()
        strokeColor2.setStroke()
        bezier4Path.lineWidth = 4
        bezier4Path.stroke()


        //// Bezier 5 Drawing
        let bezier5Path = UIBezierPath()
        bezier5Path.moveToPoint(CGPointMake(group.minX + 0.62512 * group.width, group.minY + 0.52474 * group.height))
        bezier5Path.addCurveToPoint(CGPointMake(group.minX + 0.56812 * group.width, group.minY + 0.48691 * group.height), controlPoint1: CGPointMake(group.minX + 0.59364 * group.width, group.minY + 0.52474 * group.height), controlPoint2: CGPointMake(group.minX + 0.56812 * group.width, group.minY + 0.50780 * group.height))
        bezier5Path.addCurveToPoint(CGPointMake(group.minX + 0.49416 * group.width, group.minY + 0.43783 * group.height), controlPoint1: CGPointMake(group.minX + 0.56812 * group.width, group.minY + 0.45985 * group.height), controlPoint2: CGPointMake(group.minX + 0.53494 * group.width, group.minY + 0.43783 * group.height))
        bezier5Path.addCurveToPoint(CGPointMake(group.minX + 0.42021 * group.width, group.minY + 0.48691 * group.height), controlPoint1: CGPointMake(group.minX + 0.45339 * group.width, group.minY + 0.43783 * group.height), controlPoint2: CGPointMake(group.minX + 0.42021 * group.width, group.minY + 0.45985 * group.height))
        bezier5Path.addCurveToPoint(CGPointMake(group.minX + 0.36320 * group.width, group.minY + 0.52474 * group.height), controlPoint1: CGPointMake(group.minX + 0.42021 * group.width, group.minY + 0.50780 * group.height), controlPoint2: CGPointMake(group.minX + 0.39468 * group.width, group.minY + 0.52474 * group.height))
        bezier5Path.addCurveToPoint(CGPointMake(group.minX + 0.30620 * group.width, group.minY + 0.48691 * group.height), controlPoint1: CGPointMake(group.minX + 0.33172 * group.width, group.minY + 0.52474 * group.height), controlPoint2: CGPointMake(group.minX + 0.30620 * group.width, group.minY + 0.50780 * group.height))
        bezier5Path.addCurveToPoint(CGPointMake(group.minX + 0.49416 * group.width, group.minY + 0.36218 * group.height), controlPoint1: CGPointMake(group.minX + 0.30620 * group.width, group.minY + 0.41813 * group.height), controlPoint2: CGPointMake(group.minX + 0.39051 * group.width, group.minY + 0.36218 * group.height))
        bezier5Path.addCurveToPoint(CGPointMake(group.minX + 0.68213 * group.width, group.minY + 0.48691 * group.height), controlPoint1: CGPointMake(group.minX + 0.59782 * group.width, group.minY + 0.36218 * group.height), controlPoint2: CGPointMake(group.minX + 0.68213 * group.width, group.minY + 0.41813 * group.height))
        bezier5Path.addCurveToPoint(CGPointMake(group.minX + 0.62512 * group.width, group.minY + 0.52474 * group.height), controlPoint1: CGPointMake(group.minX + 0.68212 * group.width, group.minY + 0.50780 * group.height), controlPoint2: CGPointMake(group.minX + 0.65660 * group.width, group.minY + 0.52474 * group.height))
        bezier5Path.addLineToPoint(CGPointMake(group.minX + 0.62512 * group.width, group.minY + 0.52474 * group.height))
        bezier5Path.addLineToPoint(CGPointMake(group.minX + 0.62512 * group.width, group.minY + 0.52474 * group.height))
        bezier5Path.closePath()
        bezier5Path.usesEvenOddFillRule = true;

        fillColor3.setFill()
        bezier5Path.fill()


        //// Rectangle 2 Drawing
        let rectangle2Path = UIBezierPath(roundedRect: CGRectMake(group.minX + floor(group.width * 0.43128 + 0.36) + 0.14, group.minY + floor(group.height * 0.00000 + 0.09) + 0.41, floor(group.width * 0.54847 + 0.16) - floor(group.width * 0.43128 + 0.36) + 0.2, floor(group.height * 0.16750 - 0.26) - floor(group.height * 0.00000 + 0.09) + 0.35), cornerRadius: 2)
        fillColor3.setFill()
        rectangle2Path.fill()


        //// Bezier 6 Drawing
        let bezier6Path = UIBezierPath()
        bezier6Path.moveToPoint(CGPointMake(group.minX + 0.15606 * group.width, group.minY + 0.25409 * group.height))
        bezier6Path.addCurveToPoint(CGPointMake(group.minX + 0.11576 * group.width, group.minY + 0.24301 * group.height), controlPoint1: CGPointMake(group.minX + 0.14148 * group.width, group.minY + 0.25409 * group.height), controlPoint2: CGPointMake(group.minX + 0.12689 * group.width, group.minY + 0.25040 * group.height))
        bezier6Path.addLineToPoint(CGPointMake(group.minX + 0.01670 * group.width, group.minY + 0.17727 * group.height))
        bezier6Path.addCurveToPoint(CGPointMake(group.minX + 0.01670 * group.width, group.minY + 0.12378 * group.height), controlPoint1: CGPointMake(group.minX + -0.00557 * group.width, group.minY + 0.16250 * group.height), controlPoint2: CGPointMake(group.minX + -0.00557 * group.width, group.minY + 0.13855 * group.height))
        bezier6Path.addCurveToPoint(CGPointMake(group.minX + 0.09731 * group.width, group.minY + 0.12379 * group.height), controlPoint1: CGPointMake(group.minX + 0.03897 * group.width, group.minY + 0.10902 * group.height), controlPoint2: CGPointMake(group.minX + 0.07504 * group.width, group.minY + 0.10901 * group.height))
        bezier6Path.addLineToPoint(CGPointMake(group.minX + 0.19637 * group.width, group.minY + 0.18953 * group.height))
        bezier6Path.addCurveToPoint(CGPointMake(group.minX + 0.19637 * group.width, group.minY + 0.24302 * group.height), controlPoint1: CGPointMake(group.minX + 0.21863 * group.width, group.minY + 0.20430 * group.height), controlPoint2: CGPointMake(group.minX + 0.21863 * group.width, group.minY + 0.22825 * group.height))
        bezier6Path.addCurveToPoint(CGPointMake(group.minX + 0.15606 * group.width, group.minY + 0.25409 * group.height), controlPoint1: CGPointMake(group.minX + 0.18523 * group.width, group.minY + 0.25040 * group.height), controlPoint2: CGPointMake(group.minX + 0.17065 * group.width, group.minY + 0.25409 * group.height))
        bezier6Path.addLineToPoint(CGPointMake(group.minX + 0.15606 * group.width, group.minY + 0.25409 * group.height))
        bezier6Path.addLineToPoint(CGPointMake(group.minX + 0.15606 * group.width, group.minY + 0.25409 * group.height))
        bezier6Path.closePath()
        bezier6Path.usesEvenOddFillRule = true;

        fillColor3.setFill()
        bezier6Path.fill()


        //// Bezier 7 Drawing
        let bezier7Path = UIBezierPath()
        bezier7Path.moveToPoint(CGPointMake(group.minX + 0.84083 * group.width, group.minY + 0.25409 * group.height))
        bezier7Path.addCurveToPoint(CGPointMake(group.minX + 0.80053 * group.width, group.minY + 0.24301 * group.height), controlPoint1: CGPointMake(group.minX + 0.82625 * group.width, group.minY + 0.25409 * group.height), controlPoint2: CGPointMake(group.minX + 0.81166 * group.width, group.minY + 0.25040 * group.height))
        bezier7Path.addCurveToPoint(CGPointMake(group.minX + 0.80053 * group.width, group.minY + 0.18952 * group.height), controlPoint1: CGPointMake(group.minX + 0.77826 * group.width, group.minY + 0.22824 * group.height), controlPoint2: CGPointMake(group.minX + 0.77826 * group.width, group.minY + 0.20429 * group.height))
        bezier7Path.addLineToPoint(CGPointMake(group.minX + 0.89962 * group.width, group.minY + 0.12378 * group.height))
        bezier7Path.addCurveToPoint(CGPointMake(group.minX + 0.98022 * group.width, group.minY + 0.12379 * group.height), controlPoint1: CGPointMake(group.minX + 0.92188 * group.width, group.minY + 0.10902 * group.height), controlPoint2: CGPointMake(group.minX + 0.95796 * group.width, group.minY + 0.10901 * group.height))
        bezier7Path.addCurveToPoint(CGPointMake(group.minX + 0.98022 * group.width, group.minY + 0.17728 * group.height), controlPoint1: CGPointMake(group.minX + 1.00249 * group.width, group.minY + 0.13856 * group.height), controlPoint2: CGPointMake(group.minX + 1.00249 * group.width, group.minY + 0.16251 * group.height))
        bezier7Path.addLineToPoint(CGPointMake(group.minX + 0.88114 * group.width, group.minY + 0.24302 * group.height))
        bezier7Path.addCurveToPoint(CGPointMake(group.minX + 0.84083 * group.width, group.minY + 0.25409 * group.height), controlPoint1: CGPointMake(group.minX + 0.87000 * group.width, group.minY + 0.25040 * group.height), controlPoint2: CGPointMake(group.minX + 0.85542 * group.width, group.minY + 0.25409 * group.height))
        bezier7Path.addLineToPoint(CGPointMake(group.minX + 0.84083 * group.width, group.minY + 0.25409 * group.height))
        bezier7Path.addLineToPoint(CGPointMake(group.minX + 0.84083 * group.width, group.minY + 0.25409 * group.height))
        bezier7Path.closePath()
        bezier7Path.usesEvenOddFillRule = true;

        fillColor3.setFill()
        bezier7Path.fill()
    }

}
